name: Download Helm Chart

on:
  workflow_dispatch:
    inputs:
      repo:
        type: string
        required: true
        description: 'The target repo name to fetch released chart packages. e.g. ("open-cluster-management-io/registration")'
      version:
        type: string
        required: true
        description: 'The target release to download the chart package, should be a valid semver. e.g. ("1.1.1")'
      chart-name:
        type: string
        required: true
        description: 'The chart package name which is used for finding the target asset. The downloading asset name will be "<chart-name>-<version>.tgz"'
      component:
        type: string
        required: false
        description: 'The component associated with the target release. Required for release tags of the form "<component>/v<version>"'

env:
  # Common versions
  PUBLISH_BRANCH: 'main'

jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Turnstyle
        uses: softprops/turnstyle@3805450be63b8c80577dc253e8c17e9132036df4 # v3.3.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          ref: ${{ env.PUBLISH_BRANCH }}
          token: ${{ secrets.OCM_BOT_PAT }}

      - name: Determine release tag
        id: release-tag
        run: |
          if [ -z "${{ github.event.inputs.component }}" ]; then
            echo "releaseTag=v${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          else
            echo "releaseTag=${{ github.event.inputs.component }}/v${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
          fi

      - uses: robinraju/release-downloader@28fc21f50d76778e7023361aa1f863e717d3d56f # v1.13
        with:
          repository: "${{ github.event.inputs.repo }}"
          tag: "${{ steps.release-tag.outputs.releaseTag }}"
          fileName: "${{ github.event.inputs.chart-name }}-${{ github.event.inputs.version }}.tgz"
          out-file-path: "charts/"
          token: ${{ secrets.OCM_BOT_PAT }}

      - name: Push Chart
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add .
          git status
          git commit -s \
            -m "Automated upload ${{ github.event.inputs.repo }} ${{ github.event.inputs.chart-name }}-${{ github.event.inputs.version }}.tgz"
          git push https://${{ github.token }}@github.com/${{ github.repository }}.git ${{ env.PUBLISH_BRANCH }}
